# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.topic=network-telemetry-normalized
kafka.consumer.group.id=elasticsearch-consumer-group

# Elasticsearch Configuration
elasticsearch.url=http://localhost:9200
elasticsearch.username=elastic
elasticsearch.password=N6Qs4E7s
elasticsearch.index.prefix=network-telemetry

# Consumer Configuration
consumer.batch.size=100
