# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.topic=network-telemetry-type-a

# Producer Configuration
producer.min.interval.ms=2000
producer.max.interval.ms=5000

# Device Configuration
device.id=ROUTER-001
device.location=DataCenter-1
