# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.input.topic.a=network-telemetry-type-a
kafka.input.topic.b=network-telemetry-type-b
kafka.output.topic=network-telemetry-normalized

# Spark Configuration
spark.checkpoint.location=checkpoint
spark.master=local[*]
